In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("data/major_CoLA_Annotated.tsv" , sep="\t")
data.head()

,remove,condition,target,text,Simple,Predicate,Adjunct,Argument Type,Arg Altern,Imperative,Binding,Question,Comp Clause,Auxiliary,to-VP,"N, Adj",S-Syntax,Determiner,Violations
0,gj04,In,1,The sailors rode the breeze clear of the rocks.,0,1,0,1,1,0,0,0,0,0,0,1,0,0,0
1,gj04,In,1,The weights made the rope stretch over the pul...,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0
2,gj04,In,1,The mechanical doll wriggled itself loose.,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0
3,cj99,In,1,"If you had eaten more, you would want less.",0,0,0,0,0,0,0,0,0,1,0,0,1,1,0
4,cj99,In,0,"As you eat the most, you want the least.",0,0,0,0,0,0,0,0,0,0,0,0,1,1,0

In [5]:
# Add textid column
data['textid'] = data.index

In [8]:
data.head()

,remove,condition,target,text,Simple,Predicate,Adjunct,Argument Type,Arg Altern,Imperative,Binding,Question,Comp Clause,Auxiliary,to-VP,"N, Adj",S-Syntax,Determiner,Violations,textid
0,gj04,In,1,The sailors rode the breeze clear of the rocks.,0,1,0,1,1,0,0,0,0,0,0,1,0,0,0,0
1,gj04,In,1,The weights made the rope stretch over the pul...,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,1
2,gj04,In,1,The mechanical doll wriggled itself loose.,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,2
3,cj99,In,1,"If you had eaten more, you would want less.",0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,3
4,cj99,In,0,"As you eat the most, you want the least.",0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,4

In [10]:
# save the data
data.to_csv("data/major_evaluate.tsv", sep="\t", index=False)